### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by meddd** [suhebit/recyclerview_loadmore_pagination#1]
hi
I used your example, but change loaddata, and get them from database. but the new data load only on start, bu when scroll they dont load. Coul I try to change code, but wihtout effect. do you know, how to resolve that problem.

**Comment by suhebit** [comment]
Hello Med,
Can you please share me the code snippet so that i can give you better solution.

**Comment by meddd** [comment]
i have resolved it. i have not corected guery with limit and offset.
